import "./globals.css";
import { Inter } from "next/font/google";

import ToastProvider from "@/components/toastProvider/ToastProvider.jsx";
import Footer from "@/layouts/footer/Footer.jsx";
import Header from "@/layouts/header/Header.jsx";

import Provider from "@/redux/provider.jsx";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Provider>
          <Header />
          <ToastProvider />
          {children}
          <Footer />
        </Provider>
      </body>
    </html>
  );
}
